language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install .[test]
before_script:
  - pip install python-coveralls 'coverage>=4.4'
  - mkdir coverage
script:
  - make coverage
after_success:
  - coveralls --data_file coverage/.coverage
